#!/usr/bin/env python3
"""
This module handles monkey patching of the pyatv library.

:copyright: (c) 2023-2024 by Unfolded Circle ApS.
:license: Mozilla Public License Version 2.0, see LICENSE for more details.
"""
# pyright: reportPrivateUsage=false

from collections.abc import Callable
from copy import copy
import logging
from typing import Any, cast

from pyatv import exceptions
from pyatv.auth import hap_tlv8
from pyatv.auth.hap_pairing import HapCredentials, PairSetupProcedure
from pyatv.auth.hap_srp import SRPAuthHandler
from pyatv.core import Core, SetupData
from pyatv.core.facade import FacadeAppleTV
from pyatv.protocols import airplay as airplay_proto
from pyatv.protocols.airplay.auth.hap import _AIRPLAY_HEADERS, AirPlayHapPairSetupProcedure, _get_pairing_data
from pyatv.protocols.airplay.auth.legacy import AirPlayLegacyPairSetupProcedure
from pyatv.protocols.airplay.pairing import AirPlayMajorVersion, AirPlayPairingHandler, AuthenticationType
from pyatv.protocols.airplay.srp import LegacySRPAuthHandler, new_credentials
from pyatv.support import error_handler
from pyatv.support.http import HttpConnection, http_connect

_LOG = logging.getLogger(__name__)
HapPairSetupProcedureFactory = Callable[[HttpConnection, SRPAuthHandler, str | None], AirPlayHapPairSetupProcedure]

_original_create_mrp_tunnel_data = airplay_proto._create_mrp_tunnel_data  # noqa: SLF001
_original_facade_connect = FacadeAppleTV.connect


def patched_airplay_hap_pair_setup(
    auth_type: AuthenticationType,
    connection: HttpConnection,
    display_name: str | None = None,
) -> PairSetupProcedure:
    """Return Pair-Setup procedure with an optional receiver-visible name."""
    _LOG.debug("Setting up new AirPlay Pair-Setup procedure with type %s", auth_type)

    if auth_type == AuthenticationType.Legacy:
        legacy_srp = LegacySRPAuthHandler(new_credentials())
        legacy_srp.initialize()
        return AirPlayLegacyPairSetupProcedure(connection, legacy_srp)
    if auth_type == AuthenticationType.HAP:
        srp = SRPAuthHandler()
        srp.initialize()
        hap_pair_setup_procedure = cast("HapPairSetupProcedureFactory", AirPlayHapPairSetupProcedure)
        return hap_pair_setup_procedure(connection, srp, display_name)

    msg = f"authentication type {auth_type} does not support Pair-Setup"
    raise exceptions.NotSupportedError(msg)


def patched_airplay_hap_pair_setup_procedure_init(
    self: AirPlayHapPairSetupProcedure,
    http: HttpConnection,
    auth_handler: SRPAuthHandler,
    display_name: str | None = None,
):
    """Initialize HAP pairing with an optional receiver-visible name."""
    self.http = http
    self.srp = auth_handler
    headers = copy(_AIRPLAY_HEADERS)
    if display_name:
        headers["X-Apple-Client-Name"] = display_name
    setup = cast("Any", self)
    setup._headers = headers  # noqa: SLF001
    self._atv_salt = None
    self._atv_pub_key = None


async def patched_airplay_hap_pair_setup_procedure_start_pairing(self: AirPlayHapPairSetupProcedure) -> None:
    """Start the authentication process.

    This method will show the expected PIN on screen.
    """
    self.srp.initialize()
    headers = cast("Any", self)._headers  # noqa: SLF001

    await self.http.post("/pair-pin-start", headers=headers)

    data = {hap_tlv8.TlvValue.Method: b"\x00", hap_tlv8.TlvValue.SeqNo: b"\x01"}
    resp = await self.http.post("/pair-setup", body=hap_tlv8.write_tlv(data), headers=headers)
    pairing_data = _get_pairing_data(resp)

    self._atv_salt = pairing_data[hap_tlv8.TlvValue.Salt]
    self._atv_pub_key = pairing_data[hap_tlv8.TlvValue.PublicKey]


async def patched_airplay_hap_pair_setup_procedure_finish_pairing(
    self: AirPlayHapPairSetupProcedure,
    username: str,  # noqa: ARG001
    pin_code: int,
    display_name: str | None,
) -> HapCredentials:
    """Finish authentication process.

    A username (generated by new_credentials) and the PIN code shown on
    screen must be provided.
    """
    # Step 1
    self.srp.step1(pin_code)
    headers = cast("Any", self)._headers  # noqa: SLF001

    pub_key, proof = self.srp.step2(self._atv_pub_key, self._atv_salt)
    data = {
        hap_tlv8.TlvValue.SeqNo: b"\x03",
        hap_tlv8.TlvValue.PublicKey: pub_key,
        hap_tlv8.TlvValue.Proof: proof,
    }
    await self.http.post("/pair-setup", body=hap_tlv8.write_tlv(data), headers=headers)

    data = {
        hap_tlv8.TlvValue.SeqNo: b"\x05",
        hap_tlv8.TlvValue.EncryptedData: self.srp.step3(name=display_name),
    }
    resp = await self.http.post("/pair-setup", body=hap_tlv8.write_tlv(data), headers=headers)
    pairing_data = _get_pairing_data(resp)

    encrypted_data = pairing_data[hap_tlv8.TlvValue.EncryptedData]
    return self.srp.step4(encrypted_data)


async def patched_airplay_pairing_begin(self: AirPlayPairingHandler) -> None:
    """Start pairing process."""
    self.http = await http_connect(self.address, self.service.port)
    self.pairing_procedure = patched_airplay_hap_pair_setup(
        (
            AuthenticationType.HAP
            if self.airplay_version == AirPlayMajorVersion.AirPlayV2
            else AuthenticationType.Legacy
        ),
        self.http,
        self._name,
    )
    self._has_paired = False
    return await error_handler(self.pairing_procedure.start_pairing, exceptions.PairingError)


def patched_create_mrp_tunnel_data(core: Core, credentials: HapCredentials) -> SetupData:
    """Create the MRP tunnel setup data. Close the AirPlay session if the tunnel connect fails.

    Without this, a failed connect leaves the AirPlay remote control session open on the Apple TV.
    """
    setup_data: SetupData = _original_create_mrp_tunnel_data(core, credentials)
    connect = setup_data.connect
    close = setup_data.close

    async def _connect() -> bool:
        try:
            return await connect()
        except BaseException:
            close()
            raise

    return setup_data._replace(connect=_connect)


async def patched_facade_connect(self: FacadeAppleTV) -> None:
    """Connect all protocols. Close the already connected protocols if connect fails or is canceled."""
    try:
        await _original_facade_connect(self)
    except BaseException:
        self.close()
        raise
