commit_message: "fix: New %language% translations from Crowdin [ci skip]"
append_commit_message: false
files:
  - source: /intg-appletv/locales/en_US/**/*.po
    translation: /intg-appletv/locales/%locale_with_underscore%/**/%original_file_name%
