name: Check Python code formatting

on:
  push:
    # always check code formatting in all feature branches
    branches-ignore:
      - l10n
    paths:
      - 'intg-appletv/**'
      - 'requirements.txt'
      - 'test-requirements.txt'
      - 'tests/**'
      - '.github/**/*.yml'
      - 'pyproject.toml'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# prevent concurrent runs of this workflow for open pull requests
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    name: Check Python code formatting
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: "3.11"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Lint with ruff
        run: |
          python -m ruff check intg-appletv
      - name: Check code formatting with ruff
        run: |
          python -m ruff format --check intg-appletv
      - name: Type check with pyright
        run: |
          python -m pyright
